version: "3.8"

services:
  db_user:
    image: library/postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin-ecommerce
      POSTGRES_DB: ecommerce
    ports:
      - target: 5432
        published: 5434
    volumes:
      - ecommerce:/var/lib/postgresql
      - ./docker/scripts:/docker-entrypoint-initdb.d
volumes:
  ecommerce: